--- 
abstract: installs all the Hatena modules
author: Kevin W. Henwood <Khen1950fx@aol.com>
build_requires: 
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-Hatena
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cache::File: 0
  Cache::FileCache: 0
  Class::Accessor::Fast: 0
  Class::Class: 0
  Class::Contract: 0
  Class::Data::Inheritable: 0
  Class::ErrorHandler: 0
  Class::Generate: 0
  Class::ISA: 0
  Class::MethodMaker: 0
  Class::Spiffy: 0
  Class::Struct::FIELDS: 0
  Class::Trigger: 0
  Clone: 0
  DB_File: 0
  Date::Parse: 0
  Digest::MD5: 0
  Encode: 0
  Encode::compat: 0
  Errno: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Temp: 0
  Filter::Util::Call: 0
  Getopt::Long: 0
  HTTP::Lite: 0
  Hatena::API::Auth: 0
  Hatena::Formatter: 0
  Hatena::Keyword: 0
  Hatena::Keyword::Similar: 0
  Heap::Fibonacci: 0
  IO: 0
  IO::All: 0
  IPC::ShareLite: 0
  Ima::DBI: 0
  Image::Info: 0
  JSON: 0
  JSON::Any: 0
  Jcode: 0
  Kwiki: 0
  Kwiki::Formatter::Hatena: 0
  Kwiki::Theme::Hatena: 0
  LWP: 0
  LWP::Authen::Wsse: 0
  List::Util: 0
  Location::GeoTool: 0
  MIME::Base64: 0
  Math::Trig: 0
  Parse::RecDescent: 0
  Pragmatic: 0
  RPC::XML: 0
  Regexp::Assemble: 0
  Spiffy: 0
  Spoon: 0
  Template: 0
  Template::Parser: 0
  Template::Plugin::Hatena: 0
  Test::Base: 0
  Test::File::Contents: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Warn: 0
  Text::Balanced: 0
  Text::Hatena: 0
  Text::Iconv: 0
  Text::Template: 0
  Time::HiRes: 0
  UNIVERSAL::moniker: 0
  URI: 0
  URI::Fetch: 0
  URI::Fetch::SimpleCache: 0
  WWW::Hatena::WanWanWorld: 0
  WebService::Hatena::AsinCount: 0
  WebService::Hatena::BookmarkCount: 0
  WebService::Hatena::Exist: 0
  WebService::Hatena::Fotolife: 0
  WebService::Hatena::Graph: 0
  WebService::SyncSBS::D2H: 0
  XML::Atom: 0
  XML::DOM: 0
  XML::LibXML: 0
  XML::LibXML::Common: 0
  XML::NamespaceSupport: 0
  XML::Parser: 0
  XML::RSS: 0
  XML::SAX: 0
  XML::Simple: 0
  XML::TreePP: 0
  XML::XPath: 0
  perl: 5.6.0
  version: 0
version: 0.01
